{% set version = "0.2.0" %}
{% set hash_type = "md5" %}
{% set hash_val = "b31e2724dc908ff6beec120a8bfdb42c" %}

package:
  name: resampy
  version: {{ version }}

source:
  fn: resampy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/r/resampy/resampy-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.8.0
    - scipy >=0.13
    - six >=1.3
    - numba >=0.32

  run:
    - python
    - setuptools # necessary for pkg_resources at runtime
    - numpy >=1.8.0
    - scipy >=0.13
    - six >=1.3
    - numba >=0.32

test:
  imports:
    - resampy

about:
  home: https://github.com/bmcfee/resampy
  license: ISC
  summary: 'Efficient signal resampling'

extra:
  recipe-maintainers:
    - bmcfee
