travis:
  secure:
    BINSTAR_TOKEN: gBPM2KxaI2GkPS47dlDNdhlBCX7lahiat7pupaaNXnxyZy11u4XbDENDr3fjVat4T3qIYFEiazIkrBT3SUcg/SFhx9F3MYTtpxEkvwPVKQSKg+1rt8mY0VpTMW1AapMjGilI0dsbUqCpbJPXFu76BHiza7hP+jNz0D1N0n+IYNK7LO4z0LqT26MNIfIoB+73Hx474oQOdY/iAPWY8TOrY4B3TH3vsHRwi3ZndXAuoKq481WBG9ZBE430nAluo3ZGsr4zYh6BZoyaQ76xlsgGY47b8Hp12VQ4nn+keg1XJhWACTjR5SLLvn2CoNDn+dRBanwuheIlp6kRQZt9OG2t5IeTyCoJFzjsVzKzmZfMKCWwdA5w76vwhUJCBS0wvuWXJ/VRxow9P+49W7aaREXJzMqVZXBgEPEBlJYdOmE9Nqf++Co0h8gOMxCNs/SbFJ86LHpIBul9f7X9BZ8BWccnGm12mSOECqLeJsx/QINaLOfzYvgFMyT0gu7vrZf0LTeclvvcagYYr/QMo35QUyvjnTsf8i/PxDf/5bSUAiLxnLnIY7A/F3W0fDfUHgPygKBnnDZ9kQI2OuYGGhK6SO5Uk/6WKUtEAt540GSCsXrRzOq/bNdGTvy0CU3wDhxxqcf8gZJLWSWwNfxcCp2EcZ66rnbdqfbs8Z+1t4nV0zwAflQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
