travis:
  secure:
    BINSTAR_TOKEN: Dh/EyEmZf1oKJJYIEHpKurHS2t4CYEo+kmbx+dwQrVmrtBsJm6Kjr65SoKTzpxWDpV7ElSy+M/qeUQ3nk9HNNPduhLuGaFddCzKgY05+kol8TuzjyhuOTtiXrjgZ8bpmyRauyuwq8Aqkcjr6NoP0HmFJFjFUO2AJdr5Zhhuib5iRj2ODyAuReXhRFRryGkYVZOFFlETLKYHXdDvL1ggUYeTYt3iTDN9OLUO7R2UBHukKNqULN98QSDbRyBfKnXBqBI/ncvGDI79z/jXQy39Qno2X4vtgxUCqGFhpgiAaMmkxBs4pqfX3IJAEhl0ZrkaDGuSAGEpea/sCnX07f2FP2DJacASUKCI2hAJkstdpIPpzZkKKZ3KssaEqPXlupFxgZVPvt38RskbYmcFha0Zgl30R6BrVvJu0DBoRsKjC7voWUSOvej3g6c/22b68ufTUq2XAfk0sD5hQMGKFMd+lv3vcUZ6bA+vjKoGtuWACI0GckhthfMYhv9a3PG5IhZAYdPwVOeyWa8PQtN5jsT8TPxoOubtC9IHhlgEk+0VoARg35FCYt4IKTXfK2C2okmcyToi+oxwQM+ooR1GEVmbkcQ9KJZcSwykNVyqmVwonIC+LyxD9sPaImmzhtkvOw0lLcksNyRs1704h91pXQn7JdaBLEKTWjJoaZ3LCvrAsWsA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
