travis:
  secure:
    BINSTAR_TOKEN: SO7utsrOH+KMn00EuZ6xzUV9vkmEapoOsuMXmJaoKgiKiMyIe7D5FpJIcSbP6yQXZ3dGuh8rTwBW5/LZSfd4mPs6h1SWtoeB/orwMA4Qrq4WYThD92Y+We4n3LqNWOWkBl7PuPR8tFq/7TaYxbR3dpkpb6EqcW9MysKJXwEYQpGfBTJKF3LxXlNEBIJUAG/okTcmTvmefNYmHlDuuffg+I+OQ82SSWFhKH2T+9qqx0v9ACgkSwD68zHAfMTYbmkF6ejYyKZgpKuARwKkpsyh4JDryI2Otg7z+Yw3kMDQ1PGmsaZQNksj6lnpHA0ZFN+4e/ykIiV+BjYam8zkpoH6GLs37h2Ygq/hXq7p+M4aoDA7YQg/qk9fLE8fgRPPu75k9Ciox6M1rzX9kn2zI3xQD+qwqofU3Gd7phjPGYT4Ix0zLEhNh7MIFw9mgouC39UAeENBBpSE8DI3Gy9gZuplWROeq2yUjY9j5aiqhyjUbt7BspMSQhP/n2xzEdZliEl8fu8K3mYh1SP46XuS4U+4w+1wYitlWiROHcuopW1FZwUJhEifSdQ+wDB13uUsK1f53xeRfnaT3nufs+cftlpdirZak+6DHT4o9ogqDogPNTYFY81zm+CDqdY1gepz36kF7X6J/wN+qEjfc0aZQSwEyNhOpdXdDGS+WNYOAW5zoCo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
