travis:
  secure:
    BINSTAR_TOKEN: iLizDzLYwW75qHXWcJXyqy1lbn5Tw/6j51XpPivRV+u7dphJReTDG52q5QVY+o3yw11n0DaHPHInEfe2x4w9Ozfr6bkr+ZErumWr6WZaMGxFsLCoXDLxiIsTkXEQSVtMW+ISWPLbMRKC7Zch7p6m8su0Lg49VjTJsQwhXEcTGW7JC2ZwCCyTUpig0dMWRIzNHX6EVYdETuHkAuGI/wGd+UanDIgqMrTISjNYMTw1djLS+QZePS933vdn86tt23A9WNYRmOaEDHuMD2Cf/oMqvXikwABKCaBQCs9NyTpaBOqgj8dxaTqRt79645trjuNqOuBJ3CWsNU88YNB2wXxYDuiQMqbIbCxHtFraFjx2fjk33mQA15jGL0m/TpVaTFDIZ6LQOmEpNELoBTxBtDE0O1FiC60I6mpOASxj1fAIY10bbxfrME5kMvS75RwANURnmmysOpzhyBytZ6gb1cCJzj7QFAC2p3Y2INm2xFJl8QmvhzC98YtDTiQMDwiTQv7Sq08O/Zrq9Xj52ie0exppo5aD2QcvCrvNlQHLDiknaXqDshSBwT21gdqr8PaBVKZlX7qKb/QsUAXf27PHIUAhOAKMmechNrS31fCeMlIA4AYs6QxGvVuyYMojp8jeePc/IkbJocMcG5gWhLdkNCBbEC1Rm+V6U0OaKMItflyQk7U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
